# shareme's jekyll config
permalink: /:categories/:year/:month/:day/:title 

# Configuration
# we exclude slides dir so html5 slide decks will not be jeckylled
exclude: [ 'slides', ".rvmrc", ".rbenv-version", "readme.md", "Rakefile", "changelog.md"]
markdown: maruku
pygments: true
lsi: false

# Custom variables
title: GrottWorkShop
tagline:  Mobile and Sever Hacking
# We are serving from github, http://username.github.com and thus need base_url set to /
# But if CNAME you would set this to a full url of the CNAME
# The in-site local hrefs incluidng posts will be
#     <a href="{{ site.base_url }}rest of url with no added pre /
# those ahrefs  with a {{ node.url}} DO NOT include a {{ site.base_url }} prefix}
base_url: /
# for search sit.url is used
url: http://shareme.github.com
keywords: Android, JBoss, Spring, Hibernate, iPhone, Eclipse IDE, Eclipse, NetBeans, RubyOnRails, Django, Python, Ruby,
                     PHP, Symfony2, Groovy, Gradle, Gant, Grails, Mobile, Java, JavaME, Symbian, JavaEE, Windows Phone,
                     Blackberry RIM, Blackberry, Scala, HTML5, PhoneGap, JQuery, Zepto, Zurby, Jenkins CI, Git, Hg, Mercurial,
                     SCM, TDD, Agile, BDD, Sikuli, Unit Testing, ObjectiveC, Apache ANT, Apache Maven, Apache IVY, GWT,
                     JSON, MySQL, SQL, ORM, Dependency Injection, Aspect Oriented Programming, Object Oriented Programming,
                     JNI, C++, Ubuntu, Linux, Unix, BSD, Apache HTTPD, GPL, FSF, Java Server Pages, Java Server Faces, 
                     Play Framework, NoSQL, LibreOffice, Latex, Eclipse BiRT, Java WAR, Java JAR, Chicago, NorthWest Indiana,
                     StartUps, Chicago Android, Chicago Hacker News, UX, Design, Responsive Design, Apache Buildr, Java AWT, Java Swing, 
                     Eclipse Java SWT, Android Application Design, Android Application User Interface Design, Android Application User Interaction Design,
                     Geolocation, Social APIs, SQlite, Jenkins, Hudson, Continuous Integration Build Servers, YAML, HAML, XML,
                     HTML, CSS, javascript, Message Ques, Enterprise Message Ques, GNU, REST APIs, SOAP APIs,
                     Startups, entrepreuner, ycombinator, hacker news, Chicago Androids, ThisWeekIn, Computer Science,
                     Software Engineering, GPS, OpenGL, NFC, Bluetooth, HAVi, iTV, Enterprise Java Beans, Object Relational Mapping,
                     Mobile Ajax, Object Oriented PHP, Object Oriented Javascript
description: GrottWorkShop(Fred Grott) is a mobile application and mobile services development one-person
                        development shop in the greater Chicago-land area(located inNorthwest Indiana). Specialities are 
                        Android, iphone, and several other mobile platforms areas including html5 and the server side 
                        infrastructure that provides the power behind mobile services. Android areeas cover java, 
                        renderscript, opengl, appwidgets, native C/C++, game frameworks and game engines,
                        background tasks, UI widgets, REST, json, dependency injection, tdd and bdd testing. Mobile 
                        services server side includes all the scripting MVC frameworks such as RoR, Django, Symfony2, 
                        and java enterpise including Spring, Hibernate, and Grails/Groovy. GWS also uses mobile cross
                        plaform framework such as Eclipse Mobile RAP and PhoneGap.

author:
  name: Fred Grott
  email: fred.grott@gmail.com
  github: shareme
  gplus: https://plus.google.com/u/0/114301140286672625486/about
  companygplus:



assets:
       ico: 'assets/ico'
       img: 'assets/img'
       js: 'assets/js'
       css: 'assets/css'
  
google:
  tracking_id: UA-23593281-1
addthis:
  pub_id: ra-4ea7e18b3e78fcd8
tynt:
  tracking_id: bveKsWa9er4AM8acwqm_6r

archive_path: /archive.html
categories_path: /categories.html
tags_path: /tags.html
# we use single quotes to avoid parsing of special characters
# be careful https has to be single quote escaped and you get no
# warning in your IDE usually, and the warning Jekyll gives will not
# point to the original line of the error 

  
# The secret to manipulating Jekyll and Liquid 
# to do your bidding is to use metadata to 
# say more with less, in this case our
# array[0] is both the title of the link
# and the filename base of the image
# so we have 
# <a href="{{array[1]" title="{{array[0]}}"}}" ><img src="{{ site.base_url}}{{ site.assets.img }}/{{array[0]}}.png"/>"
followme:
  angellist: 'http://angel.co/fred-grott'
  delicious: 'http://www.delicious.com/shareme'
  deviantart: 'http://shareme.deviantart.com/'
  dribbble: 'http://dribbble.com/FredGrott'
  facebook: 'https://www.facebook.com/fred.grott?ref=tn_tnmn'
  forrst: 'https://forrst.com/people/fredgrott'
  googleplus: 'https://plus.google.com/u/0/114301140286627625486/about'
  linkedin: 'http://www.linkedin/in/shareme'
  quora: 'http://www.quora.com/Fred-Grott'
  reddit: 'http://www.reddit.com/user/fredgrott'
  stackoverflow: 'http://stackoverflow.com/users/237740/fred-grott'
  twitter: 'https://twitter.com/#!/fredgrott'
  youtube: 'http://www.youtube.com/user/memine44?feature=mhee'
  
powered:
  eclipse: 'http://www.eclipse.org'
  github: 'http://github.com'
  hacker: 'http://www.fsf.org'
  jekyll: 'https://github.com/mojombo/jekyll'

myrepos:
  github: 'https://github.com/shareme'  
  bitbucket: 'https://bitbucket.org/fredgrott'  
 


 
